version: "3.9"

services:

  persistence:
    image: pokemonlitepersistence:1.0.0
    ports:
      - "4002:4002"
    stdin_open: true
    tty: true
    container_name: pokemonlite-persistence-service
    working_dir: /fileio
    #depends_on:
    #  - db
    volumes:
      - ./:/fileio:xro

  controller:
    image: pokemonlitecontroller:1.0.0
    ports:
      - "4001:4001"
    stdin_open: true
    tty: true
    container_name: pokemonlite-controller-service
    depends_on:
      - persistence

  #tui:
  #  image: pokemonlitetui:1.0.0
  #  ports:
  #    - "4003:4003"
  #  stdin_open: true
  #  tty: true
  #  read_only: false
  #  container_name: pokemonlite-tui
  #  depends_on:
  #    - persistence
  #    - controller
  #  environment:
  #    UNO_SERVICE_HOST: uno
  #    UNO_SERVICE_PORT: 8082
  #    PERSISTENCE_SERVICE_HOST: uno-persistence-service
  #    PERSISTENCE_SERVICE_PORT: 8081
  #    PERSISTENCE_SERVE_PATH: /persistence/
  #    CORE_SERVICE_HOST: uno-core-service
  #    CORE_SERVICE_PORT: 8080
  #    CORE_SERVICE_PATH: /controller/
  #
  #
  #uno-gui:
  #  image: pokemonlitegui:1.0.0
  #  ports:
  #    - "4004:4004"
  #  container_name: pokemonlite-gui
  #  depends_on:
  #    - persistence
  #    - controller
  #  network_mode: "host"
  #  volumes:
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - ~/.Xauthority:/root/.Xauthority
  #  environment:
  #    - DISPLAY=ip$0
  #    - UNO_SERVICE_HOST=uno
  #    - UNO_SERVICE_PORT=8082
  #    - PERSISTENCE_SERVICE_HOST=uno-persistence-service
  #    - PERSISTENCE_SERVICE_PORT=8081
  #    - PERSISTENCE_SERVE_PATH=/persistence/
  #    - CORE_SERVICE_HOST=uno-core-service
  #    - CORE_SERVICE_PORT=8080
  #    - CORE_SERVICE_PATH=/controller/