version: "3.9"

services:

  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "6432:5432"

  persistence:
    image: ghcr.io/luis-stumpf/pokemonlite-persistence:latest
    ports:
      - "4002:4002"
    stdin_open: true
    network_mode: "host"
    depends_on:
      - mongo  # db
      - db
      - couchdb  # db
    tty: true
    container_name: pokemonlite-persistence
    working_dir: /fileio
    volumes:
      - ./:/fileio:xro

  controller:
    image: ghcr.io/luis-stumpf/pokemonlite-controller:latest
    ports:
      - "4001:4001"
    stdin_open: true
    network_mode: "host"
    tty: true
    container_name: pokemonlite-controller
    depends_on:
      - persistence

  tui:
    image: ghcr.io/luis-stumpf/pokemonlite-tui:latest
    ports:
      - "4003:4003"
    stdin_open: true
    tty: true
    read_only: false
    container_name: pokemonlite-tui
    network_mode: "host"
    depends_on:
      - persistence
      - controller
  
  

  # gui:
  #   image: ghcr.io/luis-stumpf/pokemonlite-gui:latest
  #   ports:
  #     - "4004:4004"
  #   container_name: pokemonlite-gui
  #   depends_on:
  #     - persistence
  #     - controller
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ~/.Xauthority:/root/.Xauthority
  #   environment:
  #     - DISPLAY=host.docker.internal:0

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always

  couchdb:
    image: couchdb:latest
    ports:
      #- "8091-8094:8091-8094"
      - "5984:5984"
      #- "11210-11211:11210-11211"
    container_name: couchdb
    restart: always
    environment:
      COUCHDB_USER: username
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:

networks:
  my_network:
