version: "3.9"

services:

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1

  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "6432:5432"

  persistence:
    image: ghcr.io/luis-stumpf/pokemonlite-persistence:latest
    ports:
      - "4002:4002"
    stdin_open: true
    network_mode: "host"
    depends_on:
      - mongo  # db
      - db
      - couchdb  # db
    tty: true
    container_name: pokemonlite-persistence
    working_dir: /fileio
    volumes:
      - ./:/fileio:xro

  controller:
    image: ghcr.io/luis-stumpf/pokemonlite-controller:latest
    ports:
      - "4001:4001"
    stdin_open: true
    network_mode: "host"
    tty: true
    container_name: pokemonlite-controller
    depends_on:
      - persistence

  tui:
    image: ghcr.io/luis-stumpf/pokemonlite-tui:latest
    ports:
      - "4003:4003"
    stdin_open: true
    tty: true
    read_only: false
    container_name: pokemonlite-tui
    network_mode: "host"
    depends_on:
      - persistence
      - controller
  
  

  # gui:
  #   image: ghcr.io/luis-stumpf/pokemonlite-gui:latest
  #   ports:
  #     - "4004:4004"
  #   container_name: pokemonlite-gui
  #   depends_on:
  #     - persistence
  #     - controller
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ~/.Xauthority:/root/.Xauthority
  #   environment:
  #     - DISPLAY=host.docker.internal:0

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always

  couchdb:
    image: couchdb:latest
    ports:
      #- "8091-8094:8091-8094"
      - "5984:5984"
      #- "11210-11211:11210-11211"
    container_name: couchdb
    restart: always
    environment:
      COUCHDB_USER: username
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:

networks:
  my_network:
