apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistence
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
      - name: persistence
        image: pokemonlitepersistence:1.0.0
        ports:
        - containerPort: 4002