name: Scala CI

on: [ push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: compile
        run: sbt compile 

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Build Project and export Coverage to Codacity
        run: sbt clean jacocoAggregate
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/scala-3.3.3/jacoco/report/aggregate/jacoco.xml

  publish-docker:
    runs-on: ubuntu-latest  # Or desired runner OS

    env:
      REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Login to Github registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build Docker image (SBT)
        run: sbt clean docker:publishLocal
      - name: push images
        run: docker push ${{env.REGISTRY}}/luis-stumpf/pokemonlite-controller:latest
